import './test-path.js';
import './test-path-basename.js';
import './test-path-dirname.js';
import './test-path-extname.js';
import './test-path-isabsolute.js';
import './test-path-join.js';
import './test-path-relative.js';
import './test-path-resolve.js';
import './test-path-zero-length-strings.js';
